#!/usr/bin/env bash

echo Total: $(squeue -halu $(whoami) | wc -l)
echo Running: $(squeue -alu $(whoami) | grep RUNNING -c)
squeue -u $(whoami) -O 'jobid:10,partition:12,name:20,numcpus:5,state:10,reason:10,timeused:12,timeleft:12,nodelist:21,workdir:60'
