#!/usr/bin/env bash

declare -a arr=("elimoss" "mdurrant" "bfremin" "tamburin" "jribado" "hsberrol" "bsiranos")

echo Reporting usage for: ${arr[@]}
for i in "${arr[@]}"
do
	echo $(sacct -S $(date --date='last month' +%Y-%m-%d) -u $i --format 'elapsedraw' | \
		sed '1,2d' | tr -d ' ' | paste -sd+ | bc)*0.12/3600 | bc | xargs echo $i last month: \$ | \
		sed 's/$ /$/g' &
done