#!/usr/bin/env python

import argparse
import os

parser = argparse.ArgumentParser(description='Simple job submission to SCG/SLURM')
parser.add_argument('-m', type=int, default=4,
                    help='memory allocation in Gb [4]')
parser.add_argument('-c', type=int, default=4,
                    help='number of cores [1]')
parser.add_argument('-t', default=24, type = int,
                    help='time allocation in hours [24]')

parser.add_argument('-n', type=str, required = True,
                    help='Name your job something pithy')
parser.add_argument('command', metavar='command', type=str, nargs='+',
                    help='command to submit to SLURM')

args = parser.parse_args()

sub = 'sbatch -J {jobname} --mail-type=ALL --mail-user=$(whoami)@stanford.edu -t {time_alloc}:00:00 -p batch -n {cores} --mem={mem} -A asbhatt -o {jobname}.stdout -e {jobname}.stderr --wrap="{command}"'.format(jobname = args.n, time_alloc = args.t, cores = args.c, mem = int(args.m)*1000, command=' '.join(args.command))

os.system(sub)