#!/usr/bin/env python

import argparse
import os

parser = argparse.ArgumentParser(description='Simple job submission to SCG/SLURM')
parser.add_argument('-m', type=int, default=4,
                    help='memory allocation in Gb [4]')
parser.add_argument('-p', type=str, default="batch",
                    help='partition [batch]')
parser.add_argument('-a', type=str, default="asbhatt",
                    help='account [asbhatt]')
parser.add_argument('-d', type=str,
                    help='Job dependency (jobid)')
parser.add_argument('-t', type=int, default=1,
                    help='number of cores [1]')
parser.add_argument('-hrs', default=6, type = int,
                    help='time allocation in hours [6]')
parser.add_argument('--mail', help="Update user on job status changes through email", action='store_true')

parser.add_argument('-n', metavar="jobname", type=str, required = True,
                    help='Name your job something pithy')
parser.add_argument('command', type=str, nargs='+',
                    help='command to submit to SLURM')

args = parser.parse_args()

sub = 'sbatch -J {jobname} -t {time_alloc}:00:00 -p {batch} -n {cores} --mem={mem} -A {acct} -o {jobname}.out -e {jobname}.err --wrap="{command}"'.format(
	batch = args.p,
	jobname = args.n,
	time_alloc = args.hrs,
	cores = args.t,
	mem = int(args.m)*1000,
	command=' '.join(args.command),
	acct = args.a
)

if args.mail:
	sub += " --mail-type=ALL --mail-user=$(whoami)@stanford.edu "

if args.d:
	print("Incorporating job dependency")
	sub += ' -d afterany:{dep}'.format(dep = args.d)

os.system(sub)
